### ISSUE TITLE
Mainline?

### ISSUE THREAD

**Issue by barabadzhi** [brotfessor/sipodev#1]
Hello @brotfessor

Thanks for the patch! :hand: :smiley:

:question:  Are you considering to send it to the mainline?

**Comment by brotfessor** [comment]
Hello,
sorry for the late reply, I rarely use the github web interface.
Upstreaming is in progress, see https://bugzilla.redhat.com/show_bug.cgi?id=1526312

**Comment by brotfessor** [comment]
It has been mainlined for quite a long time now, so I am closing this.

[commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9ee3e06610fdb8a601cde59c92089fb6c1deb4aa)
