### ISSUE TITLE
Include Trekstor Primebook C11

### ISSUE THREAD

**Issue by foer** [brotfessor/sipodev#2]
Hello @brotfessor ,

thanks for all your efforts! 

Cloud you also include the Trekstor Primebook´s C13 small brother Trekstor C11? I´ve tested your patch an the Touchpad is working fine with it!

DMI Data:
cat /sys/class/dmi/id/sys_vendor
TREKSTOR
cat /sys/class/dmi/id/product_name 
Primebook C11

Thanks!

**Comment by brotfessor** [comment]
Thank you, I will include that.
