### ISSUE TITLE
Working on a SCHNEIDER SCL142ALM

### ISSUE THREAD

**Issue by Andandaran** [brotfessor/sipodev#6]
Hi brotfessor,

I compiled the kernel 5.0.0-25 (ubuntu 18.04) modifying the "i2c_hid_dmi_desc_override_table" to add:
 {
  .ident = "SCHNEIDER SCL142ALM",
  .matches = {
   DMI_EXACT_MATCH(DMI_SYS_VENDOR, "SCHNEIDER"),
   DMI_EXACT_MATCH(DMI_PRODUCT_NAME, "SCL142ALM"),
  },
  .driver_data = (void *)&sipodev_desc
 },

And it's working fine.

```
# uname -a
Linux albert-sch 5.0.0-25-custom #3 SMP Thu Aug 29 20:59:09 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux

# dmesg | grep i2c
[    2.650454] i2c /dev entries driver
[    6.056678] i2c_hid i2c-SYNA3602:00: i2c-SYNA3602:00 supply vdd not found, using dummy regulator
[    6.056727] i2c_hid i2c-SYNA3602:00: Linked as a consumer to regulator.0
[    6.056729] i2c_hid i2c-SYNA3602:00: i2c-SYNA3602:00 supply vddl not found, using dummy regulator
[    6.885561] input: SYNA3602:00 0911:5288 Mouse as /devices/pci0000:00/0000:00:17.0/i2c_designware.4/i2c-4/i2c-SYNA3602:00/0018:0911:5288.0001/input/input14
[    6.887013] input: SYNA3602:00 0911:5288 Touchpad as /devices/pci0000:00/0000:00:17.0/i2c_designware.4/i2c-4/i2c-SYNA3602:00/0018:0911:5288.0001/input/input15
[    6.887137] hid-generic 0018:0911:5288.0001: input,hidraw0: I2C HID v1.00 Mouse [SYNA3602:00 0911:5288] on i2c-SYNA3602:00
[    6.973362] input: SYNA3602:00 0911:5288 Touchpad as /devices/pci0000:00/0000:00:17.0/i2c_designware.4/i2c-4/i2c-SYNA3602:00/0018:0911:5288.0001/input/input17
[    6.974409] hid-multitouch 0018:0911:5288.0001: input,hidraw0: I2C HID v1.00 Mouse [SYNA3602:00 0911:5288] on i2c-SYNA3602:00
[ 8021.741901] drm_dp_i2c_do_msg: 156 callbacks suppressed

# cat /sys/class/dmi/id/product_name 
SCL142ALM
# cat /sys/class/dmi/id/sys_vendor 
SCHNEIDER

```
Now I'm trying to install ubuntu 20.04 and the problem persist.

Please, can you send this entry to the mainline kernel. Currently I don't have a powerful enough PC to compile the new kernel.

Than you.

**Comment by brotfessor** [comment]
Thanks for the entry. I have sent a patch out and it is already applied to the [HID queue for Linux 5.7](https://git.kernel.org/pub/scm/linux/kernel/git/hid/hid.git/commit/?id=6507ef10660efdfee93f0f3b9fac24b5e4d83e56), so it is probably going into the final 5.7 release.

Unfortunately I don't know, whether or when it is going to be applied to the Ubuntu kernels. But I have tagged it for stable so there is a good chance it will be picked up sooner or later.

**Comment by Andandaran** [comment]
When mainland was rc4 the patch was in the linux-next source, but it is not yet in mainland rc5, it is still in linux-next. I will try again with the next rc and I will tell you when it is working.

**Comment by Andandaran** [comment]
Finally working in stable 5.7.1 (Tested with ubuntu kernel-ppa/mainline)

**Comment by Andandaran** [comment]
Working on last ubuntu 20.04.1 kernel official update Ubuntu-5.4.0-45.49 (apt update; apt dist-upgrade)
